### ISSUE TITLE
result-image-format not working

### ISSUE THREAD

**Issue by megha-n-bodke** [CrackerakiUA/ngImgCropFullExtended#101]
I applied  result-image-format="image/jpeg" to img-crop.
But cropped image is always defaults to "image/png" header.
Here is the codepen:
http://codepen.io/megha_bodke/pen/YqeEdW
![inspectoutput](https://cloud.githubusercontent.com/assets/13938070/14435310/e7357560-0034-11e6-8d0b-c3e205d70790.png)

**Comment by CrackerakiUA** [comment]
Angular and javascript thing: when you want to add string as parameter, you need to add 'Text' so it don't recognize as variable.
And try to search the Issues before you post, there are like 3 same posts closed.
http://codepen.io/Crackeraki/pen/VaQQPG

**Comment by megha-n-bodke** [comment]
My Bad :(
"result-image-format="'image/jpeg'" is working fine.

**Comment by CrackerakiUA** [comment]
All cool :)
