### ISSUE TITLE
Issues with "//" URI strings and CORS

### ISSUE THREAD

**Issue by ghost** [CrackerakiUA/ngImgCropFullExtended#102]
Script only applies crossOrigin = 'anonymous' if the string starts with "http", however, many devs will simply use "//" to avoid issues mixing insecure with secure content.

Changing line 2491 to
`if (imageSource.substring(0, 4).toLowerCase() === 'http' || imageSource.substring(0, 2) === '//') {`
seems to fix the issue

**Comment by CrackerakiUA** [comment]
on next compile it will be fixed
