### ISSUE TITLE
ColorThief is not defined 

### ISSUE THREAD

**Issue by alex88** [CrackerakiUA/ngImgCropFullExtended#104]
I've just installed this library and if i include the unminified version with webpack I get:

```
ColorThief is not defined
```

in the `new ColorThief()` line

**Comment by CrackerakiUA** [comment]
this has to do with ColorThief not having index.js? I don't have any experience with webpack. If you solve it make pr, so other users can use it.

**Comment by alex88** [comment]
If you look at the various exports of the modules you have in your file you see each one has a different way to export the module :)

Anyway, this should solve the issue https://github.com/alex88/ngImgCropFullExtended/commit/257a04430ed7f60dc36c36f47f9a8baadfe1fcb0 but I'm not sure you should export other libraries code in your library

**Comment by CrackerakiUA** [comment]
I do agree it's bad idea, when i took the project, it was already there.

**Comment by ybian** [comment]
For others encountering this issue, there is workaround without touching the code. Just disable the broken module styles using `imports-loader` webpack plugin, like this:

`require('imports?define=>false,exports=>false!ng-img-crop-full-extended/compile/unminified/ng-img-crop.js')`

It works for me.

**Comment by CrackerakiUA** [comment]
So this is solved?

**Comment by ybian** [comment]
@CrackerakiUA For this specific issue, it is resolved, at least for me. But the way of this repo to handle dependencies is kind of problematic, as revealed by this issue. That might be a long term objective. ;-)

**Comment by CrackerakiUA** [comment]
If i were writing code as you do, with webpack, i would do work to make it that way

**Comment by Samerkassem** [comment]
> For others encountering this issue, there is workaround without touching the code. Just disable the broken module styles using `imports-loader` webpack plugin, like this:
> 
> `require('imports?define=>false,exports=>false!ng-img-crop-full-extended/compile/unminified/ng-img-crop.js')`
> 
> It works for me.

I am working on a old project, and I couldn't figure out a way to do this with the new webpack.

Here's my config: 

```
      {
        test:  require.resolve('ng-img-crop-full-extended/compile/unminified/ng-img-crop'),
        loader: 'imports-loader?define=>false,exports=>false',
      },
```

@CrackerakiUA  got any idea? What's the other way?

**Comment by CrackerakiUA** [comment]
I am not working with that tech, so sorry, I can't help with that :(
