### ISSUE TITLE
Original Bit depth is not retrived after cropping the image 

### ISSUE THREAD

**Issue by sureshb4u** [CrackerakiUA/ngImgCropFullExtended#106]
Hi @CrackerakiUA .First of all thanks for this plugin,  I am using it  in my project It is really awesome.
One thing I noticed is that the  Bit Depth of the cropped image is always 32-bit, 
When I upload a 24-bit image the plugin making it 32 bit and it increases the size of the image which is greater than the original image 
I couldn't find where the bit depth is calculated in the plugin it would be great if we get the cropped image with bit depth same as the original one

**Comment by CrackerakiUA** [comment]
i will check this as soon as i can.

**Comment by sureshb4u** [comment]
Hi CrackerakiUA ,do we have any update on this.

**Comment by CrackerakiUA** [comment]
Not yet. I am kinda busy with main projects.
