### ISSUE TITLE
Importing with JSPM

### ISSUE THREAD

**Issue by patrickmichalina** [CrackerakiUA/ngImgCropFullExtended#108]
It would be nice if this would be distributed in such a way that JSPM could import it naturally. It works, but may not be clear to new users. For anyone looking in the future, import it like this:

```
import "ng-img-crop-full-extended/compile/unminified/ng-img-crop.js";
```

Otherwise you will get a token unexpected error because the package is not conforming to the standard.

**Comment by rickerd** [comment]
Hi @patrickmichalina 
I updated the Wiki with your information.
https://github.com/CrackerakiUA/ngImgCropFullExtended/wiki/Installing

I hope this helps other developers that use JSPM in the future.

Thanks
