### ISSUE TITLE
Square crop going out of bounds

### ISSUE THREAD

**Issue by ghost** [CrackerakiUA/ngImgCropFullExtended#109]
Can reproduce here: http://codepen.io/Crackeraki/pen/XmEdPx

<img width="731" alt="screen shot 2016-05-13 at 5 02 06 pm" src="https://cloud.githubusercontent.com/assets/7838694/15261820/88303652-192c-11e6-9e3e-4f42b134971e.png">

Using an image that's landscape, If you square crop and extend from the bottom right node, the square will become taller than the canvas. It results in graphical issues and odd behaviour.

**Comment by CrackerakiUA** [comment]
Damn, this were fixed by me 2 months ago ...
i will check in few days.

**Comment by DavideRoss** [comment]
Any news on this?

**Comment by CrackerakiUA** [comment]
didn't had the time, will try as soon as i can.

**Comment by rickerd** [comment]
@CrackerakiUA already found time?

**Comment by CrackerakiUA** [comment]
@rickerd not yet.
