### ISSUE TITLE
result-image-quality not working for result-blob

### ISSUE THREAD

**Issue by zmkpr0** [CrackerakiUA/ngImgCropFullExtended#110]
I believe it should be 

`temp_canvas.toBlob(function(blob) {
                _p.resolve(blob);
            }, resImgFormat, resImgQuality);`

instead of 

`temp_canvas.toBlob(function(blob) {
                _p.resolve(blob);
            }, resImgFormat);`

**Comment by CrackerakiUA** [comment]
make PR
