### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by bbales** [CrackerakiUA/ngImgCropFullExtended#114]
This issue referenced from [here](https://github.com/alexk111/ngImgCrop/issues/126)

FYI - In the crop_host.js the destroy function wrong:

```
$document.off('mouseup',onMouseMove);
$document.off('touchend',onMouseMove);
```

should actually be

```
$document.off('mouseup',onMouseUp);
$document.off('touchend',onMouseUp);
```

This is causing a significant memory leak.

**Comment by CrackerakiUA** [comment]
make pr

**Comment by rickerd** [comment]
Since he wouldn't do it, i did it.
https://github.com/CrackerakiUA/ngImgCropFullExtended/pull/131

**Comment by rickerd** [comment]
Close plz because its already merged
