### ISSUE TITLE
Get accurate cropImageWidth on large portrait images?

### ISSUE THREAD

**Issue by ronaldjeremy** [CrackerakiUA/ngImgCropFullExtended#116]
Our use case of this tool is to load images and POST crop coordinates to the server which will crop the original image using those coordinates.  

It works fine for larger landscape images, but it looks like if a large image with portrait EXIF orientation gets loaded, then the canvas gets shrunk to a max of 1000px.  That makes the cropImageWidth etc coordinates inaccurate.  Is there a way to be able to get accurate crop coordinates even though the canvas got shrunk?

**Comment by CrackerakiUA** [comment]
You can resize image to 1920_1080 max (ex 1795_1080 or 1920*1071) and use that image on cropper and after crop get points for actual crop on the server.

**Comment by ronaldjeremy** [comment]
That will not work.  That would reduce the quality of the source image, resulting in a lower quality cropped area.

I do not know how to do a pull request, but this is what I did:

I added an additional field called "downScale" to cropject.  That number will be 1, unless the "[3, 6, 8].indexOf(orientation) > -1" in setNewImageSource is hit, in which case downScale will be what the "p" variable is there".

With the downScale number, then I can get the original image width in my controller doing something like:
origWidth = Math.round(vm.cropper.cropImageWidth / vm.cropper.downScale)

**Comment by CrackerakiUA** [comment]
if you have fixed your issue then you are ok. My solution is working, i am actually using it on my projects.

**Comment by ronaldjeremy** [comment]
I am unclear on what your solution is.  Are you saying that you resize the source image to 19201080 max on your computer before uploading it to crop?

**Comment by CrackerakiUA** [comment]
no no, javascript. You keep scale of the image and make max 1920 width and max 1080 height. In that way you get smooth cropping tool. After that you send to the server the original image alongside with object from cropobject and handle the cropping inside back-end as you wish. I am using ImageMagick on back-end which do a bit better work from canvas.

**Comment by CrackerakiUA** [comment]
If you wish i can drop here the code of that resize, actually i have other service doing it, which i build my self. I can share resize code.

**Comment by ronaldjeremy** [comment]
Yes please, that would be awesome!  I am also using ImageMagick on server.  In my case the server already has the source image (for the crop tool i am using like `<img-crop image="'http://myserver.com/someimage.jpg'")>`, then i am just passing to the server the area i want to crop for the image that is already there.

**Comment by CrackerakiUA** [comment]
So you simply have to send cropobject to server, i will add code for resize soon.

**Comment by CrackerakiUA** [comment]
```
var reader = new FileReader();
reader.onload = function (loadEvent) {
    var ratioToFloat = function(val) {
        var r = val.toString(),
            xIndex = r.search(/[x:]/i);
        if (xIndex > -1) {
            r = parseFloat(r.substring(0, xIndex)) / parseFloat(r.substring(xIndex + 1));
        } else {
            r = parseFloat(r);
        }
        return r;
    };
    var canvasElement = document.createElement('canvas');
    var imageElement = document.createElement('img');
    imageElement.onload = function() {
        var ratioFloat = ratioToFloat(1920/1080);
        var imgRatio = imageElement.width / imageElement.height;
        if (imgRatio < ratioFloat) {
            width = 1920;
            height = width / imgRatio;
        } else {
            height = 1080;
            width = height * imgRatio;
        }
        canvasElement.width = width;
        canvasElement.height = height;
        var context = canvasElement.getContext('2d');
        context.drawImage(imageElement, 0, 0 , width, height);
        var dataURL = canvasElement.toDataURL('image/png', 1);
        scope.$apply(function () {
            // here you have dataURL of the resized image
        });
    };
    imageElement.src = loadEvent.target.result; // loadEvent.target.result it's the src of the image        
};
```

Hope this will help you out.

**Comment by ronaldjeremy** [comment]
fantastic, thank you!
