### ISSUE TITLE
prevent resize

### ISSUE THREAD

**Issue by El4a** [CrackerakiUA/ngImgCropFullExtended#121]
Hi!

is it possible to prevent the box from being resized? As in I set a default size, and the user can not resize it, only move it around to capture a different part of the image?

Or does anyone know of a different library that does this?

**Comment by CrackerakiUA** [comment]
We don't have such option, i guess it could be cool option.

**Comment by thierryskoda** [comment]
+1

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
