### ISSUE TITLE
support for cropping GIFS

### ISSUE THREAD

**Issue by joanitad** [CrackerakiUA/ngImgCropFullExtended#122]
hi @CrackerakiUA ,
Does this have support for GIFS ? 
I tried changing the result-image-format="'image/gif'" .
http://codepen.io/anon/pen/pbgwQp
What can I do to add GIF cropping capability to this ?

**Comment by CrackerakiUA** [comment]
How do you imagine this? Max best result could be first frame cropped.

**Comment by joanitad** [comment]
ok, thanks :-)
