### ISSUE TITLE
Unable to install package using bower

### ISSUE THREAD

**Issue by joanitad** [CrackerakiUA/ngImgCropFullExtended#124]
hi @CrackerakiUA ,
I am unable to install the package using bower . I need to use bower for my project. I tried searching for the package using bower search and couldn't find it either. 

npn install works fine, but I need bower install.

**Comment by CrackerakiUA** [comment]
well, i think it was working normally, at the moment it don't have latest code but it should work. You can't download any code at all?

**Comment by joanitad** [comment]
i can't download any code at all. 
I get this error : 
`bower install ngImgCropFullExtended
bower                        ENOTFOUND Package ngImgCropFullExtended not found`

**Comment by CrackerakiUA** [comment]
I will check tomorrow why it's not working, it should.

**Comment by joanitad** [comment]
Hi @CrackerakiUA ,
Any updates on the package install using bower ?

**Comment by CrackerakiUA** [comment]
https://bower.io/search/
add ngImgCropFullExtended

**Comment by joanitad** [comment]
Thanks that worked!
