### ISSUE TITLE
Example ngImgCrop use different sizes

### ISSUE THREAD

**Issue by ignacio-chiazzo** [CrackerakiUA/ngImgCropFullExtended#128]
This example shows you how to use the ngImg with different sizes https://github.com/ignacio-chiazzo/ngImgCropTool-Examples.

**Comment by rickerd** [comment]
Cool, can we do something with it @CrackerakiUA ?
I think it can be closed.

**Comment by ignacio-chiazzo** [comment]
@rickerd @CrackerakiUA https://github.com/CrackerakiUA/ngImgCropFullExtended/pull/137

**Comment by CrackerakiUA** [comment]
@ignacio-chiazzo i have checked this before, i can't see the use of this. But if others need it, i could accept PR for sure.
