### ISSUE TITLE
Error with webkitURL

### ISSUE THREAD

**Issue by eliseguimaraes** [CrackerakiUA/ngImgCropFullExtended#129]
Chrome tells me webkitURL is deprecated.
window.webkitURL doesn't return null, but the method createObjectURL doesn't exist, which is why I changed the code on line 3057 - which was:
`scope.urlBlob = urlCreator.createObjectURL(blob);`
 to:
`scope.urlBlob = window.webkitUrl.createObjectURL ? window.webkitURL.createObjectURL(blob) : window.URL.createObjectURL(blob);
`

**Comment by rickerd** [comment]
In what version of Chrome does this happen?
There is an test folder that has all the new code and i don't see this coming up?

If there you really have troubles with the urlCreator please create a PR with your fix.

**Comment by rickerd** [comment]
Closing no error in Chrome is happening.
Other people also had problems but use the lib. correctly now.
https://github.com/CrackerakiUA/ngImgCropFullExtended/pull/142#issuecomment-241171440
