### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MaximilianLloyd** [CrackerakiUA/ngImgCropFullExtended#133]
Sadly I will not a be able to use this fork until this issue is resolved. It crashes on startup without any sort of error message. An example is shown below:
![2016-07-09_22-06-54](https://cloud.githubusercontent.com/assets/10583205/16710013/852d35be-4621-11e6-877f-ec25272c2905.gif)

**Comment by CrackerakiUA** [comment]
never seen this before.

**Comment by MaximilianLloyd** [comment]
yeah it sucks. Will have to use the original lib until the issue gets resolved. I tried it on both my laptop and my desktop but it yielded no difference.

**Comment by rickerd** [comment]
@CrackerakiUA are there any major diffrences between this fork and the original version?
I still convinced that the libs. should be merged and that we go furter with 1 big and good plugin.

**Comment by CrackerakiUA** [comment]
@rickerd alex is not active, he is not merging. We have added many functionality to the plugin. @MaximilianLloyd to let us help you, you have to create a codepen and reproduce the issue you have. Ovewise it could be some other issue on your project.

**Comment by achubai** [comment]
I have the same issue

**Comment by CrackerakiUA** [comment]
@achubai good, please create codepen so we can see it too.

**Comment by achubai** [comment]
@CrackerakiUA
I can't reproduce it on codepen, maybe reason in webpack, and that I have to use [this](https://github.com/CrackerakiUA/ngImgCropFullExtended/issues/104#issuecomment-223236336)

**Comment by CrackerakiUA** [comment]
If so, then i can't help you out. I am not user of such things.

**Comment by CrackerakiUA** [comment]
But you are welcome to modify our lab so it continue to work on codepen and on your projects.

**Comment by SakshiParakh** [comment]
@CrackerakiUA 
It crashes foe me at the startup as well, with the error message: "Uncaught TypeError: Cannot set property 'MegaPixImage' of undefined"

**Comment by CrackerakiUA** [comment]
@SakshiParakh Will love to fix the codepen you gonna create to show me the error.

**Comment by rickerd** [comment]
Closing issue for the reason it cannot be reproduced by us or other people in Codepen.
I think it's project depended
