### ISSUE TITLE
While cropping can we give default size and location for the cropper

### ISSUE THREAD

**Issue by sunojvijayan** [CrackerakiUA/ngImgCropFullExtended#134]
Hi Can I set a default size and location for the cropper to appear. Like I want the cropper to appear at say y=100px, x= 50px and what the cropper to have length 400px and height 150px

**Comment by CrackerakiUA** [comment]
http://codepen.io/Crackeraki/pen/YqKwzZ
this should work for you. Reopen if not.

**Comment by sunojvijayan** [comment]
I was able to change the location using 

area-init-coords="{x: 0, y: 0}"

But I need to change the location based on the screen width and height. So is there a way we can change this dynamically like

area-init-coords="{{cropLocation}}"

and in controller

$scope.cropLocation = "{x: 0, y: 0}"

Can this be done

**Comment by CrackerakiUA** [comment]
i am not using area-init, haven't build it, so i don't know about this option. In the example i send you exists cropobject, which provide you the controll over croparea from your controller.

**Comment by sunojvijayan** [comment]
Solved it with this. Thanks. ##135
