### ISSUE TITLE
Cant import library into project

### ISSUE THREAD

**Issue by DmitryVolkovTulaco** [CrackerakiUA/ngImgCropFullExtended#136]
Using webpack + es6 + angular.
Expression import ngImgCrop from 'ng-img-crop-full-extended'; shows me an error 'Module not installed'.
Possible solution - create index.js file in root folder, with following code - require("./compile/unminified/ng-img-crop.js");
module.exports = "ngImgCrop";

But in result I still have an error in browser ReferenceError: ColorThief is not defined.
Any ideas?

**Comment by CrackerakiUA** [comment]
i am not user of webpage, i can't help.

**Comment by rickerd** [comment]
Hi @DmitryVolkovTulaco 

@CrackerakiUA and i haven't worked with webpack.
I personally don't know how to help you with this problem.

Maybe it's an option to ask this on Stackoverflow? And if you have an answer, reopen this issue with a solution.

Sorry but the bets of luck to get it fixed.
