### ISSUE TITLE
Firefox Zero Width/Height Canvas Print Issue

### ISSUE THREAD

**Issue by joelcdoyle** [CrackerakiUA/ngImgCropFullExtended#140]
Hello. I came here from the original ngImgCrop repo. Noticed the request for them to drop the repo and transfer here due to inactivity and thought I would share this issue here as well as there.

This is a weird one, but it is worth mentioning. There is a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1019551) that prevents a page from printing if there is a canvas element with width and height of `0`. This is exactly the element that is placed in the DOM when ngImgCrop is initialized.

Steps to reproduce:
1. Open [demo page](http://crackerakiua.github.io/ngImgCropFullExtended/) in Firefox (I'm using 47, the latest stable as of this issue)
2. Try to print, either with browser UI, or console `window.print()`
3. Observe error message : "There was an unexpected problem while printing."
4. Using the FF dev tools, either remove the canvas node, or set the canvas node width and height to something greater than zero
5. Observe that printing functions now work properly

Obviously, FF is to blame for this one, but if there is a workaround that makes sense to add to this repo, I would certainly appreciate it. A couple of suggestions:

Is there someway to set the canvas element to `width="1"` and `height="1"` on initialization, or NOT place the canvas into the DOM until the user interacts with the directive, AND to remove the canvas once the user is done with directive?

NOTE: The issue is not reproduceable in the JSFiddle for the original ngImgCrop, I'm guessing due to iframe encapsulation.

I've attempted to use CSS:

``` css
img-crop {
  canvas {
    min-width: 1px;
    min-height: 1px;
  }
}
```

But this doesn't work

Completely removing the canvas node from the DOM, or manually setting width and height to something greater than zero with the inspector are the only things that restore printing functions.

**Comment by joelcdoyle** [comment]
Ugh. Looks like I can simply use an ng-if to determine whether or not to show the directive at all. Problem solved.

**Comment by lidasong** [comment]
i get the same issue,the ng-if can solve the problem,but the issue is not existed always.do you have any other method to solve the issue ? waiting ....
