### ISSUE TITLE
Dynamic result image size (rectangular crop with aspect ratio)

### ISSUE THREAD

**Issue by bojan-stankovic** [CrackerakiUA/ngImgCropFullExtended#145]
I see that after crop if I haven't specified the result image size, I will get a square image with the excess becoming transparent. My question is: is it possible to have dynamic result image size based on the cropped area selected?

**Comment by CrackerakiUA** [comment]
something like this? http://codepen.io/Crackeraki/pen/XmEdPx
It give you scale of crop area.

**Comment by bojan-stankovic** [comment]
I was talking about this: http://prntscr.com/c6wndo
I set the aspect ratio to be 3, haven't specified result image size, and i get the cropped image + the transparent part added to make it square. I was wondering can I get the result image without the transparent part without specifying the width and height.

**Comment by CrackerakiUA** [comment]
strange, shouldn't work like that. To be honest, when i set aspect ration, i always set result size. Need to fix that.

**Comment by CrackerakiUA** [comment]
By the way, if you fix it we would love to accept your PR

**Comment by bojan-stankovic** [comment]
If I find time, I will definitely check it out. Currently my workload is overwhelming. For now I will stick to setting result size. 

Btw thank you for your quick response.

**Comment by taint2310** [comment]
I have same issue.

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
