### ISSUE TITLE
what is the best way to reuse the crop area?

### ISSUE THREAD

**Issue by cxnunes** [CrackerakiUA/ngImgCropFullExtended#148]
Hi, I am using your plugin for edit and crop an array of images but, for each one I am saving the cropject in order to edit each image from the last crop option. I am setting these attributes from the scope object that i change according each pictures, but sometimes the size of the crop area doesn't change when i set these attributes. Could you give me an help?
result-image-size="{w:main.cropper.cropWidth,h:main.cropper.cropHeight}"
area-init-coords="{y:main.cropper.cropTop,x:main.cropper.cropLeft}"
area-init-size="{w:main.cropper.cropWidth,h:main.cropper.cropHeight}"

**Comment by rickerd** [comment]
Is it not better to use another language to crop An array of images?
Like php?

**Comment by cxnunes** [comment]
So forget the array part. My biggest question is to keep the my crop area options in a scope object and when open the cropper again I could set the options (position and size of the crop area). The position is working well but the set of the size is not working properly.

**Comment by CrackerakiUA** [comment]
from your code i can see that you are not using array of images. Please provide some codepen so we can check what you want to success.

**Comment by cxnunes** [comment]
With the array I just want to say that I have a set of images that I will crop in different times manually. So each one per time. My question is just if I save the cropject that you provide from the directive, for each image after cropped it, the next time I want to edit the crop area of a respective image I want to continue from the last "crop state" that is the cropject that I saved before. So which attributes should I set to properly open the cropper tool with a specific crop area defined by x,y,w,h? The attributes I tried were the ones i identified before but maybe I missing some. Thanks

**Comment by rickerd** [comment]
I think from your text / story that you need to save the last state yourself.
The complete cropject that is used and returned needs te be saved in 1 piece everytime.

The logic isnt in the cropper but in your own JavaScript.

Save the object in your images array but use angular.copy() to NOT reffer to the same object or variables.

**Comment by cxnunes** [comment]
Yes, that part of saving the cropject I am already doing it. 

My question is which attributes on the img-crop directive should be set everytime I want to set the new crop area according the saved cropject?

**Comment by CrackerakiUA** [comment]
make multiple ng-crop and toggle them with ng-if.

**Comment by rickerd** [comment]
Closing the issue since it has no issue towards the repo itself
