### ISSUE TITLE
New repo to drop fork

### ISSUE THREAD

**Issue by rickerd** [CrackerakiUA/ngImgCropFullExtended#151]
@CrackerakiUA i've asked @janruehling to drop his original ngImgCropFullExtended repo so we can use this repo name and not to have a fork anymore.
We do alot of development on the plugin and since the original person doens't answer.. i think it's the best option.

We can start a clean project on our own repository.

~~https://github.com/janruehling/ngImgCropFullExtended/issues/1#issuecomment-243390022~~

**Comment by janruehling** [comment]
@rickerd ... done

**Comment by rickerd** [comment]
@CrackerakiUA  I've "claimed" the repo name. Gimme a heads up if i need to delete the repo so you can make it your own.
Or if you say screw it we can go on under my name.
I personally don't care.

**Comment by janruehling** [comment]
I just deleted my repo ... go for it under your name if you like.

I don't use Angular anymore ... so no need to keep it attached to my name :-)

**Comment by rickerd** [comment]
What do you use nowadays @janruehling?

**Comment by janruehling** [comment]
CycleJs Diversity -- with RxJs v5
