### ISSUE TITLE
Can't install with angular 1.4.12

### ISSUE THREAD

**Issue by TM1584875DM** [CrackerakiUA/ngImgCropFullExtended#154]
In bower.json:
"dependencies": {
    "angular": "1.4.0"
}
why not use "~1.4.0" ? Or angular version must be "1.4.0" ?

**Comment by rickerd** [comment]
Yesterday i've also seen this dependency and scratched my head.
I personally use angular 1.5.x in my project and it all works fine.
Do you @CrackerakiUA know why its failing?

I am working on a compile and test in Travis so im hoping to make better coverage and tests along the way.

**Comment by CrackerakiUA** [comment]
first time see this also )
i am also using latest angular 1.

**Comment by rickerd** [comment]
I will update this in master

**Comment by simison** [comment]
Hi! Does this work with Angular v1.5.x? :-) If it does, bower could be updated to reflect that.

**Comment by rickerd** [comment]
Yes + its already updated.
Check the master branch and bower.json file

**Comment by simison** [comment]
`~1.4.0` matches only up to Angular `1.4.x`, not Angular `1.5.x`. You could require e.g. `>=1.4.0 <1.6.0`, `>=1.4` or just `1.*` instead.

Newest Angular v1 is `1.5.8`, `.9` just around the corner.

https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/bower.json#L50

http://semver.org/
http://jubianchi.github.io/semver-check/

**Comment by rickerd** [comment]
Okay, make a PR for it.
Sorry i thought it worked with ~1.4

We can use your help

**Comment by simison** [comment]
^ done. 🍻
