### ISSUE TITLE
Add repo to Travis

### ISSUE THREAD

**Issue by rickerd** [CrackerakiUA/ngImgCropFullExtended#157]
Can you add this repo to [Travis Ci](https://travis-ci.org/)?
And invite me to the Travis repo so i can see and test stuff.

**Comment by CrackerakiUA** [comment]
Please do. I don't use it.

**Comment by rickerd** [comment]
You need to do this, i am not a owner of the repository.
And add me to Travis so i can see the repo too

**Comment by CrackerakiUA** [comment]
How do i give you access?

**Comment by rickerd** [comment]
I dont know exactly. Did you already added your repo to Travis?

**Comment by CrackerakiUA** [comment]
https://travis-ci.org/CrackerakiUA/ngImgCropFullExtended

**Comment by CrackerakiUA** [comment]
there is nowhere where i can give you access
i think it's public data, all can see it. On next push if file is there, you will see results there.

**Comment by rickerd** [comment]
Perfect. I will try something.

**Comment by rickerd** [comment]
Still jshint is failing but the build says passed. I want 100% jshint or else fail.

**Comment by rickerd** [comment]
Its all fixed now 👍 
Travis will fail if the standards are not met in JSHint. And will ignore the 3rdparty libs.

**Comment by CrackerakiUA** [comment]
Cool, i will check it when i can.
