### ISSUE TITLE
Move to an organisation?

### ISSUE THREAD

**Issue by simison** [CrackerakiUA/ngImgCropFullExtended#161]
This seems to be pretty well maintained lib! How about making something about this:

![screen shot 2016-09-04 at 23 10 03](https://cloud.githubusercontent.com/assets/87168/18233612/bc9b2150-72f4-11e6-8462-b3b141d63579.png)

E.g. I wanted to do code-search for something in this repo and it's not possible for forks in GitHub. :-(

Also adds credibility => that adds usage => adds more PRs. We'd like to use+spread this trough [Meanjs](https://github.com/meanjs/mean), but this fork-of-a-fork status is kinda off-putting. :-/

Even call it something else than "ngImgCropFullExtended"?

How about moving to https://angular-ui.github.io/ ?

**Comment by rickerd** [comment]
I'm trying my best to make something of the repo.
@CrackerakiUA is the original forker and since a short while im contributing.
I've added a detailed demo page and optimized the bower, npm and gulp files. (but with a little bug that you showed me)

But if i understand you correctly, you want to add this repo to AngularUI and make it part of the AngularUI family.

**Comment by CrackerakiUA** [comment]
It will be honor for us to be part of family AngularUI.

**Comment by simison** [comment]
- Simply transferring to `github.com/CrackerakiUA/newname` wouldn't work: https://help.github.com/articles/about-repository-transfers/
- You'd have to create a new repo either at `github.com/angular-ui/newname` or `github.com/CrackerakiUA/newname`: and then do something like this: https://gist.github.com/manakor/8972566
- Contact Angular-UI guys if you're interested: https://groups.google.com/forum/#!forum/angular-ui  (I'm not associated)

**Comment by CrackerakiUA** [comment]
ok thanks @simison

**Comment by CrackerakiUA** [comment]
https://groups.google.com/forum/#!topic/angular-ui/NdkT-f2Bhh8

**Comment by rickerd** [comment]
What about this? Im not seeing any activity, what can/should we do?

**Comment by CrackerakiUA** [comment]
@rickerd i guess they don't need cropper.

**Comment by rickerd** [comment]
I think so too. So why... not do it our own :D
Screw the fork and start a new name / cropper with a own organisation.

**Comment by CrackerakiUA** [comment]
@rickerd i am planning too, but not now. Going to make allot of modifications, on that point i will create new lib. At the moment people are following this one, so i guess i will keep it for now.

**Comment by rickerd** [comment]
What could be done is create a new lib. and remove this one (commits and README) and put in the new README that the repo has been moved.
Maybe that's an option.
I think it better to close this one for now..

**Comment by CrackerakiUA** [comment]
I will think about it. My problem is that we will change bower install and on older project that can be an issue.
