### ISSUE TITLE
Result is "image/png" when "image/jpeg" was requested via resultImageFormat

### ISSUE THREAD

**Issue by FirstVertex** [CrackerakiUA/ngImgCropFullExtended#163]
When I send in the option for `result-image-format='image/jpeg'` it is ignored by ngImgCropFullExtended.

Here is Codepen with the issue:
http://codepen.io/anon/pen/WGvjRX

You see the `result-image-format` is set to `image/jpeg`.  Go ahead and do a crop.  Now inspect element on the cropped image and you see the format is actually `image/png`

Similarly, the options for `resultImageQuality` and `resultImageSize` are ignored.

**Comment by FirstVertex** [comment]
ok, i see that it is requiring a binding for these parameters.  so when i create a string value for "image/jpeg" in my viewmodel, and bind it to the option, it works.

i guess i did not understand that this option requires a binding.  is there any way to just pass a string in, straight from the markup?

here is Codepen that works.  it uses binding for these parameters
http://codepen.io/anon/pen/bwdWrL

**Comment by rickerd** [comment]
Okay, so in the end there's no problem?
Only a misunderstanding i assume.

**Comment by FirstVertex** [comment]
yes. sorry for the confusion. it works fine when i bind the value to controller.
