### ISSUE TITLE
Aspect Ratio Bug

### ISSUE THREAD

**Issue by tmclemons** [CrackerakiUA/ngImgCropFullExtended#168]
I am finding limitations to the aspect ratio attribute for the ngimgcrop directive. If the image is too narrow or the aspect ratio is too long for example 4:1, (width : height), the cropper on the canvas starts breaking or blacking out sections of the result image.

Please advise.

<img width="519" alt="screen shot 2016-09-13 at 1 18 33 pm" src="https://cloud.githubusercontent.com/assets/2036192/18483883/18c508cc-79b4-11e6-82c9-8549a65563fe.png">
<img width="669" alt="screen shot 2016-09-13 at 1 17 45 pm" src="https://cloud.githubusercontent.com/assets/2036192/18483894/20a3dfd2-79b4-11e6-9b15-92b56e9949f8.png">

**Comment by CrackerakiUA** [comment]
@tmclemons ok, i see the issue. I will checkup.

**Comment by tmclemons** [comment]
@CrackerakiUA thanks, do you have any guess where a fix for this may lie in the code?

**Comment by CrackerakiUA** [comment]
@tmclemons this looks to be some sort of fixing going off crop area from the image. Looks to take more then it needs. Which is kinda strange, i will checkup when i can. This is urgent for you?

**Comment by tmclemons** [comment]
@CrackerakiUA semi urgent, we want to use this feature for our app, but we need to do a fixed rectangular cropping  at an aspect ratio for 1920px by 250px. If we cannot solve this issue we may either disable image cropping or have to go with another image cropping solution :(. Any help would be appreciated.

**Comment by daangeerdink** [comment]
+1 I also have this issue, using 5:1 aspect ratio.

**Comment by lermion** [comment]
- 1 I also have this issue using 1.7 aspect ratio, i see this bug if image have resolution 750 x 1334, can you show me which part of code is response for it? maybe i can fix it

**Comment by ghost** [comment]
is this case fixed already? or maybe there is another way for this case?

**Comment by rickerd** [comment]
This repo is dead. Move to the other updated project please.
https://github.com/CrackerakiUA/ui-cropper
