### ISSUE TITLE
Cropper doesn't work on most Android mobile browsers

### ISSUE THREAD

**Issue by ozknemoy** [CrackerakiUA/ngImgCropFullExtended#171]
it is real to change situation?

**Comment by rickerd** [comment]
Testes on iOS 10.0.1 with safari 10
Works like a charm
![Screenshot of iOS 10 cropper](http://i.imgur.com/jKb27Qk.jpg)

**Comment by ozknemoy** [comment]
i have been testing on android: mozilla, chrome, yandex and CM. works only on chrome. appeared message undefined and nothing more

**Comment by rickerd** [comment]
Which version of the cropper are you using?
And what does your console say?

**Comment by ozknemoy** [comment]
6.1 localy and from http://codepen.io/Crackeraki/pen/XmEdPx . console keeps silent

**Comment by rickerd** [comment]
Weird, it works on my phone.
I cannot reproduce since i don't own Android products.
Maybe you can download locally and debug the translation messages as that is the last feature we added.

**Comment by ozknemoy** [comment]
v5.0 also not work for me on mobile. v6.1 i installed only 3 hours ago

**Comment by rickerd** [comment]
Plz help us find out what is causing this.
Personally i don't know what could be wrong but if you install it locally and run the example in the example folder it should be easier to debug where it goes wrong

**Comment by ozknemoy** [comment]
mozillas console showed error: palette is null. but only once

**Comment by ozknemoy** [comment]
very strange. when i click button test image it works. if i choose image from disk it do not
by the way image fills only one quarter its field
![123](https://cloud.githubusercontent.com/assets/16036508/18635281/8d4b362c-7e95-11e6-9bb2-fdaadff95cef.png)

**Comment by rickerd** [comment]
I know, i haven't found out wat is causing this.
I use the cropper on a project too and it doesn't go crazy like this.

**Comment by AlexSwensen** [comment]
Can you confirm you have the latest version of [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en) installed on your devices?

**Comment by ozknemoy** [comment]
no i am not have it.  is this  a cause?

**Comment by AlexSwensen** [comment]
I would install it and see if things improve.

**Comment by ozknemoy** [comment]
tried on two android 5  phones with WebView. one is ok, second is not

**Comment by AlexSwensen** [comment]
Which phones? Out of curiosity.

**Comment by ozknemoy** [comment]
first was Sony Xperia d2303, second - huawei p8

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
