### ISSUE TITLE
Cropject rounding error affecting width

### ISSUE THREAD

**Issue by FirstVertex** [CrackerakiUA/ngImgCropFullExtended#174]
In my application I have a minimum image size of 300x300.  I give realtime feedback if the cropped image is too small.  I do this by looking in `cropject` during `on-change`.

The problem is, frequently the dimensions in the cropject are 299x300.  There seems to be a rounding error that is setting the `cropject.cropImageWidth` 1px too small in the width.  Sometimes it is also 299x300 when I initialize with the `init-max-area` which I would expect it to initialize to 300x300.

Here is Codepen with the issue:
http://codepen.io/anon/pen/rrmymm

1) Select an image
2) Drag the crop circle
3) Notice the discrepancy between cropject (width=299) and actual image (width=300)

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
