### ISSUE TITLE
Does not work with internet explorer 11

### ISSUE THREAD

**Issue by vincaslt** [CrackerakiUA/ngImgCropFullExtended#183]
I cannot successfully implement crop tool in internet explorer 11, because of `InvalidStateError` poping up every time. The error can also be seen in examples provided in readme: `http://codepen.io/Crackeraki/pen/XmEdPx`

I have tried several different versions, and I find, that this particular error is not present until around version ~0.4.4. However, it does not work too, because it treats optional parameters as undefined and throws errors into console (might have to do with angular being version 1.5.8) in IE11.

**Comment by CrackerakiUA** [comment]
@vincaslt i just opened my internet explorer and everything worked smoothly on the codepen.

**Comment by vincaslt** [comment]
Can I ask if you're using windows 10?

Because it's funny, on windows 10 with IE 11 I am not getting any errors. At work on windows 7 with IE11 I get the same error as on IE10 on windows 10...

**Comment by CrackerakiUA** [comment]
yes, i am using windows 10

**Comment by CrackerakiUA** [comment]
install windows 10 where you have windows 7 xD

**Comment by vincaslt** [comment]
Yeah, so I thought. Try compatibility mode for IE10 to see the error I'm having on windows 7.

It say's it's on line 1722: `http.responseType = 'arraybuffer';`
SCRIPT5022: InvalidStateError

**Comment by CrackerakiUA** [comment]
need to find old laptop to check it.

**Comment by vincaslt** [comment]
Well to be sure, I guess. But for a quick look, you can change IE version via developer tools

**Comment by sdeprez** [comment]
I confirm the issue with IE11 (on windows 7), on [the same line](https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/compile/unminified/ng-img-crop.js#L1722). Setting the response type _after_ opening the request seems to fix the issue. More informations on this problem:
http://stackoverflow.com/questions/20760635/why-does-setting-xmlhttprequest-responsetype-before-calling-open-throw
https://connect.microsoft.com/IE/feedback/details/795580/ie11-xmlhttprequest-incorrectly-throws-invalidstateerror-when-setting-responsetype

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
