### ISSUE TITLE
result-image-quality is not reducing my image size

### ISSUE THREAD

**Issue by bmwertman** [CrackerakiUA/ngImgCropFullExtended#184]
I had originally been using [ngImgCrop](https://github.com/alexk111/ngImgCrop) the non-full extended version. I moved to `ngImgCropFullExtended` because I needed some of the other features. 

With `ngImgCrop` I was setting `result-image-quality=0.6` in my template along with `result-image-format="image/jpeg"` and getting my cropped image size down to around 5-7KB. 

After moving to `ngImgCropFullExtended` using the same settings I'm at 50-60KB.

Nothing else changed but the lib.

**Comment by CrackerakiUA** [comment]
Interesting. I will do tests.

**Comment by bmwertman** [comment]
Thanks let me know what you find or if you need some more info.

**Comment by bmwertman** [comment]
Have you had a chance to look into this?

**Comment by mitomm** [comment]
I can confirm a similar issue. Not only can't I reduce the image size with the `result-image-quality` property, my final Image size is actually much bigger (900kb) than the initial image I upload (100kb).

Any help would be greatly appreciated.

**Comment by diedona** [comment]
I updated to the ui-cropper and it worked. But i needed to pass it as a string:

`result-image-format="'image/jpeg'"`

ui-cropper: https://github.com/CrackerakiUA/ui-cropper

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
