### ISSUE TITLE
Centering the cropped image in the result-image-size

### ISSUE THREAD

**Issue by inv-egrant** [CrackerakiUA/ngImgCropFullExtended#185]
Looking over the options I am not seeing one where if the crop is smaller than the result-image-size it will place the crop in the center of the result-image-size.

**Comment by CrackerakiUA** [comment]
You are welcome to add one.

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
