### ISSUE TITLE
"area-coords" not relative to raw image

### ISSUE THREAD

**Issue by mrjeanjean** [CrackerakiUA/ngImgCropFullExtended#186]
Hi there,
First, thanks for this plugin. You did a very good job. That's help me so much.

I wondered about getting the area crop coords relative to the original image model. Because when I use the attribute area-coords, it gives to me the crop zone coords.

For instance if I upload a 2000x2000 size image and ask for 150x150 cropped image, area-coords with _init-max-area="true"_ will give to me {"x":0,"y":0,"w":150,"h":150}. I'd like to get {"x":0,"y":0,"w":2000,"h":2000}.

 Is it implemented in your plugin or I need to it implement by myself ?

The example in Plunker : https://plnkr.co/edit/0IANTezERj2lfv28t0oT

Thanks.

**Comment by rickerd** [comment]
I do it myself too and i use a time-out to do the magic

**Comment by mrjeanjean** [comment]
Ok ! You're contributor so did you pull a request for this or just for your own usage?

**Comment by rickerd** [comment]
No its just how the cropper works.
I wrote my own thing in a Angular Controller

**Comment by mrjeanjean** [comment]
Thanks for your feedback.

**Comment by thierryskoda** [comment]
@rickerd Is it possible to have a preview of your solution ?

Thanks you!
