### ISSUE TITLE
New Repo?

### ISSUE THREAD

**Issue by RobbertWolfs** [CrackerakiUA/ngImgCropFullExtended#188]
In the READ.ME the following is written.

> Important Notes
> We are going to move this lib to new repo. We will accept here Pull Requests until 16 October. After move we will leave this lib as it is, so on your projects it will work forever, just without updates, deprecated. 17 October you will have access to new repo.

Since it is already the 20th, what would be the new repo?

Thanks :)

**Comment by CrackerakiUA** [comment]
Sorry for the delay, new repo is published, but not completed.
https://github.com/CrackerakiUA/ui-cropper
Probably tomorrow will fix everything.

**Comment by RobbertWolfs** [comment]
No problem, thanks for the quick response.

Awesome! 💯 
Probably going to need it as of tomorrow or even Monday so thats good 👍
