### ISSUE TITLE
some images cropping doesn't work in Firefox but it's working in Chrome

### ISSUE THREAD

**Issue by sanchig** [CrackerakiUA/ngImgCropFullExtended#193]
mostly all images upload and crop successfully but some kind of image doesn't upload & crop. image showing successfully in form but while I am going to select quare and crop that image I am getting bellow error in firefox console. but same image working chrome. Please give me suggestion and thanks in advance.

"This plugin is deprecated in the name of ui-cropper. You can find it under https://github.com/CrackerakiUA/ui-cropper" ng-img-crop.js:2
DOMException [IndexSizeError: "Index or size is negative or greater than the allowed amount"
code: 1
nsresult: 0x80530001
location: http://aks.wishbook.com/vendor/ngImgCropFullExtended-master/compile/minified/ng-img-crop.js:2]

image looks like when I select square to drop another place
![error in firefox](https://cloud.githubusercontent.com/assets/16812387/22680384/9f2eca50-ed2d-11e6-97e4-b856c2363338.png)

**Comment by CrackerakiUA** [comment]
Do you have this error with ui-cropper?

**Comment by singhmohancs** [comment]
@CrackerakiUA 
Getting the same warning.

<img width="949" alt="screen shot 2017-02-15 at 11 17 49 pm" src="https://cloud.githubusercontent.com/assets/283132/22987526/12969114-f3d5-11e6-9593-630cbd5e62cf.png">

<img width="656" alt="screen shot 2017-02-15 at 11 18 13 pm" src="https://cloud.githubusercontent.com/assets/283132/22987524/128d4cda-f3d5-11e6-8fc5-6044bbdeafe0.png">

<img width="1090" alt="screen shot 2017-02-15 at 11 17 57 pm" src="https://cloud.githubusercontent.com/assets/283132/22987525/1295dad0-f3d5-11e6-90b5-e10390dbcf8c.png">

Should I use `ui-cropper`?

**Comment by CrackerakiUA** [comment]
i am not supporting this lib anymore, i have moved to ui-cropper. If you have issue with lib, you can add that bug into ui-cropper, if it's exists on that lib.

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
