### ISSUE TITLE
Ocassional NPE in ColorThief.prototype.getColor

### ISSUE THREAD

**Issue by DallanQ** [CrackerakiUA/ngImgCropFullExtended#197]
Every once in awhile, getPalette returns null, which causes palette[0] to throw an error. 

    ColorThief.prototype.getColor = function(sourceImage, quality) {
        var palette = this.getPalette(sourceImage, 5, quality);
        var dominantColor = palette[0];
        return dominantColor;
    };

I've created an issue on lokesh/color-thief#131 but I thought you'd like to know. It looks like getColor can just return null if palette is null; would that harm anything?

**Comment by CrackerakiUA** [comment]
I haven't seen that error before.

**Comment by DallanQ** [comment]
It doesn't happen very often; maybe once a week. It could be related to a particular browser/OS combination, or maybe some weird way I'm using ngImgCropFullExtended; I don't know. But it looks like all you do with the result of getColor is set scope.dominantColor. You don't actually use scope.dominantColor, right?

**Comment by CrackerakiUA** [comment]
i am not sure, i don't use that code before.

**Comment by DallanQ** [comment]
Thanks. I've just hacked around it: var dominantColor = !!palette ? palette[0] : null; hopefully that will solve the issue I'm getting.
