### ISSUE TITLE
Initial size of the crop area

### ISSUE THREAD

**Issue by evdoks** [CrackerakiUA/ngImgCropFullExtended#24]
In my use case the initial size of the cropping area must as large as possible: depending on the size of the image and aspect ration, either width or height should span the whole dimension of the image.

Currently it is a minimum of  one half of the corresponding dimension or `200` (`resetCropHost()` in `crop-host.js`):

```
theArea.setSize({
    w: Math.min(200, cw / 2),
    h: Math.min(200, ch / 2)
});
```

It might be useful to introduce a parameter (e.g., `initCropSize` between 0 and 1) that allows defining the initial size of the crop area: e.g.,

```
theArea.setSize({
    w: Math.min(200, cw * initCropSize),
    h: Math.min(200, ch * initCropSize)
});
```

However, I am not quite sure how what is the nice way to implement it since `resetCropHost()` has no access to the scope of the directive. Any ideas?

**Comment by CrackerakiUA** [comment]
Why do you need this access? Which is the problem with the way you build it `theArea.setSize({
    w: Math.min(200, cw * initCropSize),
    h: Math.min(200, ch * initCropSize)
});`

**Comment by evdoks** [comment]
Well, because if I want to control it via a parameter, the parameter will be attached to the scope.

**Comment by DallanQ** [comment]
+1 This is a _terrific_ library - thank you! It would be really nice if I could set the initCropSize as a parameter.

**Comment by DallanQ** [comment]
There appears to be one more change that needs to be made, in addition to theArea.setSize change mentioned above. I also had to change the theArea.setCenterPoint call in the setMaxDimensions function to 

```
 theArea.setCenterPoint({
   x: ctx.canvas.width / 2,
   y: ctx.canvas.height / 2
 });
```

for an initCropSize of 1. If I don't do this, the initial crop size is reduced in the setCenterPoint call. My change is clearly a hack(TM), but I'm not sure what the correct change is.

**Comment by 9mm** [comment]
Darn I need this too. I tried to do this with area-min-size but when the cropper loads it doesnt load the minimum size, so I can't use that as a workaround.

Is there anyway to do this without forking it?

**Comment by 9mm** [comment]
It looks like area-coords could do it, but it's not even in the original codebase?

**Comment by CrackerakiUA** [comment]
Need to check it out. If in original it is working normally, i am pretty sure i can fix it quickly.

**Comment by 9mm** [comment]
that would be amazing. PS I found the original area-coords, I didn't notice github doesnt let you search on forked repos... Either way, I still am not quite sure how to use area-coords or if that even helps.

Really I just want to set it on the max size immediately as the cropper loads. `area-coords="{w: 500, h: 500}"`

**Comment by CrackerakiUA** [comment]
best would be `area-coords="'max'"`, that will help cases where we can aspect ratio

**Comment by 9mm** [comment]
yes, that would be amazing.

**Comment by DallanQ** [comment]
Agreed

**Comment by karensg** [comment]
+1

**Comment by mavrick** [comment]
+1 please

**Comment by CrackerakiUA** [comment]
+1 :)

**Comment by hughred22** [comment]
+1

**Comment by rickerd** [comment]
+1

**Comment by rickerd** [comment]
I looked at the project and the initial forker/starter didn't had alot of time, at least that's what he said.
Here is my PR [https://github.com/CrackerakiUA/ngImgCropFullExtended/pull/64](url)

**Comment by rickerd** [comment]
@CrackerakiUA the init feature is made and merged. This can be closed
