### ISSUE TITLE
Mobile Safari issue

### ISSUE THREAD

**Issue by crazy8brown** [CrackerakiUA/ngImgCropFullExtended#25]
Has anyone seen an issue when trying to use the live demos from a mobile device, specifically from iPhone/Safari or Chrome?  When I select an image from my camera roll, the app hangs on the loading message. I've replicated this with my own app on a mobile (works fine on desktop Chrome emulating a mobile device).  I'm not sure how best to try and debug the issue, outside of simply saying it doesn't work. Sorry I can't give more specifics.

**Comment by CrackerakiUA** [comment]
Do you trying this from webpage or something like phonegap?

**Comment by crazy8brown** [comment]
From a webpage.  If you point a mobile browser to one of your demo sites, you can replicate the behavior.   I tried it on this: http://codepen.io/Crackeraki/full/XmEdPx/  Thanks for looking into this.

**Comment by xJoshx** [comment]
This happens in Safari desktop version too. Any solution?

**Comment by evdoks** [comment]
I believe it happens due to 

```
newImage.crossOrigin = 'anonymous';
```

in `crop-host.js`.
The original ngCrop repo adds `crossOrigin` property only for images loaded via `http`. In case of a local file `crossOrigin` must not be set - check commit [d244d01](https://github.com/alexk111/ngImgCrop/tree/d244d0164a7de62a34aad054ebb984b856a510ab). Here is the [PR](https://github.com/CrackerakiUA/ngImgCropFullExtended/pull/51).

**Comment by allanesquina** [comment]
It's happening on Firefox 35.0.1 as well
http://codepen.io/Crackeraki/pen/avYNKP
![image](https://cloud.githubusercontent.com/assets/3584636/12948135/4a53b374-cfe7-11e5-8ffc-b590854aaecf.png)

**Comment by allanesquina** [comment]
@evdoks Thanks, your commit is working :)
how about update it on bower?

**Comment by CrackerakiUA** [comment]
i will do one soon

**Comment by aramiscubillo** [comment]
Thanks for fixing this :D

**Comment by rickerd** [comment]
Is this already fixed? @CrackerakiUA i think it is.. But a PR #51 says there is still something wrong?

**Comment by simison** [comment]
@rickerd looks like mentioned issue with blobs is already being handled: https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/source/js/classes/crop-host.js#L482-L484
