### ISSUE TITLE
Error: [$parse:syntax] result-image-format="{}"

### ISSUE THREAD

**Issue by Molnfront** [CrackerakiUA/ngImgCropFullExtended#28]
Hi,
I tried to switch from alexk111 ngImgCrop version to yours so I can crop with rectangle. But then result-image-format stops working if I set a dynamic variable like this: result-image-format="{format}". It works in alexk111 latest ngImgCrop.

I have tried both with result-image-format="{format}" and result-image-format="{{format}}"

Error Parse Syntax: Syntax Error: Token '}' is unexpected, expecting [:] at column 8 of the expression [{format}] starting at [}]. 

Example:
format set in controller:
$scope.format = 'image/jpeg';

<img-crop image="myImage" area-type="rectangle" result-image="myCroppedImage"
       result-image-quality="1"
       result-image-size="{w:600, h:600}"
       result-image-format="{format}"></img-crop>

Here is a codepen:
http://codepen.io/Molnfront/pen/wMwQZa

**Comment by CrackerakiUA** [comment]
ok i see your point, here is how it should be http://codepen.io/Crackeraki/pen/GoKepX
but again, result is png, i will check it.

**Comment by CrackerakiUA** [comment]
it will work with `$scope.format`, just use it this way: `result-image-format="format"`. But again, i need to fix this first.

**Comment by Molnfront** [comment]
Yes, I imagined it should work as alexk111 ngImgCrop version. Also result-image-size="{w:600, h:600}" works as expected in your version so I think it was a bit strange when it wasn't working with variables in result-image-format.

I also tried with $scope.format = "image/jpeg" and in the html: result-image-format="format" but it will not get converted to a variable.

**Comment by Molnfront** [comment]
I will give my users the possibility to choose if they would like to crop the picture or not with a little checkbox. I am looking to build a more flexible solution with angularjs and fabric.js in the future.

**Comment by CrackerakiUA** [comment]
I will fix this as soon as possible.

**Comment by CrackerakiUA** [comment]
http://codepen.io/Crackeraki/pen/PZEjKo
