### ISSUE TITLE
Version 0.4.5 minified version differs from non-minified version

### ISSUE THREAD

**Issue by thetathaurus** [CrackerakiUA/ngImgCropFullExtended#29]
Hi, 
the previous fix from version 0.4.4 to 0.4.5 (crop selection stops at invisible border on portrait oriented images) is not included within the minified version. Could you rebuild and release again?

in t.prototype._preventBoundaryCollision

i.y+a>r&&(i.y=r-a)) 
should be 
i.y+a>t&&(i.y=t-a)) 

Thanks

**Comment by CrackerakiUA** [comment]
I am not sure where is that, can you show me in which merge we had this?

**Comment by thetathaurus** [comment]
It was the merge from "Nov 30, 2015": Hash 8574a3c8716c2e233b2442e535455ba4d141cfb6.
The unminified version is fine, but the minified one has the problem.

**Comment by keyCat** [comment]
Hi

The current version of `master` branch should include the aforementioned fix in a minified version. However, it is not possible to get this version via Bower (needs tagging?), but you can use this in your `bower.json` as temporary solution for the time being:

``` json
  "dependencies": {
    "ngImgCropFullExtended": "0bffb754aee910c122dc7052d22f8961ebf301cc"
  }
```

It will point Bower to commit 0bffb754aee910c122dc7052d22f8961ebf301cc which has rebuilt sources.
Hope that helps.

**Comment by thetathaurus** [comment]
great, thanks for your response

**Comment by CrackerakiUA** [comment]
i will update bower today.
