### ISSUE TITLE
Error on image load

### ISSUE THREAD

**Issue by ksr583** [CrackerakiUA/ngImgCropFullExtended#31]
Error: [$compile:nonassign] Expression 'undefined' used with directive 'imgCrop' is non-assignable!

The directive is being used as such:

```
      <img-crop area-type="square"
                image="photo.myImage"
                result-image="photo.myCroppedImage"
                area-coords="photo.areaCoords">
      </img-crop>
```

My even handler is as such:

```
  photo.handleFileSelect = function(evt) {
    var file = evt.currentTarget.files[0]
    var reader = new FileReader()
    reader.onload = function (evt) {
      $scope.$apply(function($scope){
        photo.myImage = evt.target.result
      })
    }
    reader.readAsDataURL(file);
  }
```

Any ideas on this?

**Comment by CrackerakiUA** [comment]
hmmm, do you have this code in some kind of modal?

**Comment by ksr583** [comment]
Yes I do

**Comment by CrackerakiUA** [comment]
Try to use small timeout

**Comment by ksr583** [comment]
Ok tried that with no luck. I also tried it on a blank template with no modal or anything. If it helps, the error is replicated any time I resize the photo, and the cropping and production of the resultImage still works. Really weird. I filed another ticket about the cropper not working in the app on IE11 or Edge, and I just can't help but wonder if these issues aren't related somehow. I have no idea.

**Comment by CrackerakiUA** [comment]
Can you see this issue in codepen example?

**Comment by ksr583** [comment]
Turns out this was an angular version issue. Upgrading to 1.4.7 fixed it. Thanks!
