### ISSUE TITLE
Not Working in IE11 or Edge

### ISSUE THREAD

**Issue by ksr583** [CrackerakiUA/ngImgCropFullExtended#33]
I'm having an issue getting this to work in IE11 or Edge. I know it's not the library itself, because the demo works fine in both. The only thing I can think of is that I'm not using a raw <input> to let the user select a file, but rather I have a button with a click listener that programmatically triggers the click on the input to bring up the browse file interface. Is that likely the issue? Does anyone have any other ideas what could be causing this?

**Comment by CrackerakiUA** [comment]
we all use button to upload the image :) I have tested on both and it is working on my side, can you show us simple demo on codepen so we can check?

**Comment by ksr583** [comment]
Turns out this was an angular version issue. Upgrading to 1.4.7 fixed it. Thanks!
