### ISSUE TITLE
It seems not working for me when the Base64 contains charset=utf-8

### ISSUE THREAD

**Issue by alsosweet** [CrackerakiUA/ngImgCropFullExtended#34]
$scope.myImage='data:image/*;charset=utf-8;base64,iVBORw0K.....

**Comment by CrackerakiUA** [comment]
can you ceate codepen with your base64?

**Comment by alsosweet** [comment]
http://codepen.io/alsosweet/pen/dGoWdy

it's ok when remove "charset=utf-8",but my raw data contains it

**Comment by CrackerakiUA** [comment]
Ok, great, i will fix this in next days. I will reply here when it's fixed.

**Comment by CrackerakiUA** [comment]
please fix the regex for your data url, which will work for dataurl without charset. The function is here https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/source/js/classes/crop-exif.js#L307
but you can drop the regex here and i will implement it.

**Comment by rickerd** [comment]
The exif.js is a library and should not be changed i think, unless there's a real bug in the library of exif.js
Also i want to install these dependencies instead of including them in our repo.

Closing due to no response + not changing a 3rd party lib.
