### ISSUE TITLE
result-image-size problem

### ISSUE THREAD

**Issue by jingjlii** [CrackerakiUA/ngImgCropFullExtended#35]
When I use two img-crop in one page, I found that the last img-crop's result-image-size's value will cover the first one's. Even though the two different imge-crop use the different controllers. How can I solve this problem?
Thanks.

**Comment by CrackerakiUA** [comment]
Please create a codepen with your problem so i can help you in more details.

**Comment by adam-showtime** [comment]
Same issue here. Lots of data is overwritten by the last imgcrop on the page. aspect-ratio,url-blob,result-image-size

**Comment by CrackerakiUA** [comment]
Can you create codepen sample for this issue?

**Comment by jingjlii** [comment]
I have created codepen: http://codepen.io/BabysbreathJJ/pen/EPPovy
The aspect-radio are different in the two image crop areas. But the result images' size are all used the last defined one. Please help me to solve this problem.  Thank you very much!

**Comment by CrackerakiUA** [comment]
![screenshot 2015-12-16 15 23 32](https://cloud.githubusercontent.com/assets/6815721/11841946/2ba1edce-a409-11e5-945a-483c21334289.png) i have something like this in your codepen, can you explain why this is wrong? I am testing i on chrome + windows 10

**Comment by jingjlii** [comment]
You can save the first result image and view it on your computer. The right side is filled with white background. Its width is equals with the second result picture.  I am on chrome + MacOS 10.10.5

**Comment by BabysbreathJJ** [comment]
[ng-image.docx](https://github.com/CrackerakiUA/ngImgCropFullExtended/files/64056/ng-image.docx)

**Comment by jingjlii** [comment]
![6 pic](https://cloud.githubusercontent.com/assets/6993633/11842780/c4b11bc0-a440-11e5-8ece-f6541eee34cf.jpg)
![1](https://cloud.githubusercontent.com/assets/6993633/11842790/e5a5d4f6-a440-11e5-9ac8-0c90fde4eb10.png)

In the developer’s tool, when I select the first result image, it shows in the ng-src that the picture’s size is equal to the second cropped result size. But I want to save a specified size picture, so can you fix this? Thanks.

**Comment by CrackerakiUA** [comment]
I will try it on mac in one hour. On windows i don't see this issue.

**Comment by CrackerakiUA** [comment]
Tested on El Capitan and Mavericks with Chrome 47, everything looks ok.

**Comment by BabysbreathJJ** [comment]
I found it's because I use the related JS file downloading by bower in my project.  When I change the url address it seems everything ii's OK. I don't know why. 
<script src="bower_components/ngImgCropFullExtended/ngImgCropFullExtended-0.4.7/compile/minified/ng-img-crop.js"></script>
<script src="https://rawgit.com/CrackerakiUA/ngImgCropFullExtended/dev/compile/minified/ng-img-crop.js"></script>

**Comment by jingjlii** [comment]
I found when I use the url https://rawgit.com/CrackerakiUA/ngImgCropFullExtended/dev/compile/minified/ng-img-crop.js
Everything is OK.

But when I use the file downloading using bower the bug show again.
Do you change something in the https://rawgit.com/CrackerakiUA/ngImgCropFullExtended/dev/compile/minified/ng-img-crop.js file?

**Comment by mavrick** [comment]
Currently seeing the same issue with the package downloaded via bower

`"ng-img-crop-full-extended": "ngImgCropFullExtended#~0.4.8"`

**Comment by CrackerakiUA** [comment]
If you download this file directly from the github everything works?

**Comment by rickerd** [comment]
Is this issue still present? Is the code already tagged from master of issue #96?
I would like to close this issue its been open since januari.

**Comment by rickerd** [comment]
No response... closing the issue
