### ISSUE TITLE
portrait from a device

### ISSUE THREAD

**Issue by adam-showtime** [CrackerakiUA/ngImgCropFullExtended#38]
Hi,
Im having problems when i try to use a image that is portrait and a large size.

**Comment by CrackerakiUA** [comment]
can you add image which you use and codepen on which you use it.

**Comment by adam-showtime** [comment]
![img_1834](https://cloud.githubusercontent.com/assets/13849212/11893437/7a149352-a568-11e5-869e-e84b7e74b80d.JPG)

use this file

**Comment by ruslan5t** [comment]
It also does not work for me.

**Comment by dazulu** [comment]
Same here. It might be related to this? https://github.com/alexk111/ngImgCrop/issues/58#issuecomment-84913160

**Comment by CrackerakiUA** [comment]
if this fixed in the original cropper?

**Comment by dazulu** [comment]
I think the original is https://github.com/alexk111/ngImgCrop, right? Correct me if I'm wrong. Just tested with it and it has the same problem.

**Comment by CrackerakiUA** [comment]
yes, it is. ok, then it's old issue.

**Comment by dharitdesai** [comment]
looks like this was fixed in pull request #88

**Comment by rickerd** [comment]
Fixed long ago
