### ISSUE TITLE
need to cancel pending $timeout in certain situations

### ISSUE THREAD

**Issue by DallanQ** [CrackerakiUA/ngImgCropFullExtended#40]
I'm using ngImgCropFullExtended inside an ng-file-upload directive following [this example](http://jsfiddle.net/xxo3sk41/1/) so I can crop images prior to upload. It's generally working well, but I have found that when the user pastes an image from the clipboard into the ng-file-upload directive, and later pastes a _different_ image, the `image` attr is updated twice: once with an empty value, and a second time with the new value. The second update happens before the $timeout in `ng-img-crop.js` from the first update has had a chance to fire. For reasons I haven't figured out, the net result is the crop area flashes with the newly-pasted image briefly, and then becomes empty. A simple work-around to this issue (I'm not sure it's the right fix, so I didn't submit a pull-request), is to add a check in `ng-img-crop.js` to see if a $timeout is pending before setting a new timeout, and if a timeout is pending, to cancel the pending timeout before setting the new one, as in:

```
            if (!!scope.timeout) {
                $timeout.cancel(scope.timeout);
            }
            scope.timeout = $timeout(function() {
                scope.timeout = null;
                cropHost.setNewImageSource(scope.image);
            }, 100);
```

**Comment by loupiz** [comment]
Had the same issue. Your fix worked for me as well. Thanks

**Comment by rickerd** [comment]
@loupiz can you make a PR with the fix in it?
I hope it can resolve alot of issues with other developers.

**Comment by rickerd** [comment]
@DallanQ can you make a PR? Even it's not the bets piece or right fix.. IF it fixed something it better then no fix.

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
