### ISSUE TITLE
Cropped result image sometime has white vertical line or horizontal line added...  

### ISSUE THREAD

**Issue by hughred22** [CrackerakiUA/ngImgCropFullExtended#42]
So this is happen randomly. When I move the crop area, it will sometime generate a white vertical or horizontal line. The whiteline is not just a dispaly problem. It will be saved into the result image and uploaded to my server. So it is destroying the image. Anyway to fix this? 

Here is my code: 

```
 <div ngf-drop class="drop-box" 
        ngf-drag-over-class="'dragover'"
        ng-model="file"
        ngf-multiple="false"
        accept="image/*">

          <img-crop image="file | ngfDataUrl" result-image="croppedDataUrl" ng-init="croppedDataUrl=''" area-type="rectangle" aspect-ratio="1.7" result-image-size='{w: 1280,h: 720}' result-image-format='image/jpeg'> 
          </img-crop>
    </div>
    <div class="preview-image" ng-show="file">
      <p>Preview:</p>

      <img ng-src="{{croppedDataUrl}}" style="width: 512px; margin-bottom: 20px;"/>
    </div>
```

**Comment by hughred22** [comment]
Also, result-image-format='image/jpeg' is not working as well. As you see my code set this up but the result image is still PNG. 

Thanks!

**Comment by hughred22** [comment]
Hi, how is this bug coming along? Still got stuck with the image type. Upload jpg turn into PNG... And png file is bigger than jpg so it is not ideal :(

**Comment by CrackerakiUA** [comment]
i tested that last night and it was working normally, can you make codepen so i can fix it?

**Comment by CrackerakiUA** [comment]
About the line, really, i have seen it too, can't imagine how it get there.

**Comment by Josmorsot** [comment]
Hello, I have the same problem as @hughred22 :

> Also, result-image-format='image/jpeg' is not working as well. As you see my code set this up but the result image is still PNG.
> Thanks!

I have this in a template:
`<img-crop result-image-format="image/jpeg" aspect-ratio="1.77" area-type="rectangle" image="imageToCrop" result-image="croppedImage" result-image-size="{w:500,h:281}"></img-crop>'`

Aspect-ratio, area-type and result-image-size are working but i get "png" format always.

I have used chrome debugging tool and I've saw in line 2795 that scope.resultImageFormat is NaN.
`scope.$watch('resultImageFormat',function(){
cropHost.setResultImageFormat(scope.resultImageFormat);
updateResultImage(scope);
});`

Any idea about what could be happening.

Thanks!

**Comment by hughred22** [comment]
Yes, I am still having this issue. I just use PNG for now but love to find out what is going wrong :)

**Comment by hughred22** [comment]
@Josmorsot Actually, I found the problem. It is actually my bad. The correct directive attribute should be result-image-format="'image/jpeg'" as image/jpeg should be string! Try this it works for me. The line issue is still there tho.

**Comment by CrackerakiUA** [comment]
i do remember this bug, actually it's high priority bug.

**Comment by CrackerakiUA** [comment]
any idea anyone, where could be this generating?

**Comment by peluprvi** [comment]
This can happen when overlapping the canvas, like was in #52

**Comment by CrackerakiUA** [comment]
I believe no, this result is watched on high resolution images on event crop type.

**Comment by rickerd** [comment]
So there is still no fix for the vertical line? :(

**Comment by CrackerakiUA** [comment]
the line is not vertical only, i have seen it horizontal more times. Yes still no fix, can't imagine where that bug is.

**Comment by CrackerakiUA** [comment]
I have success to fix this on my projects but i am using only the cropper info about locations and original dataURL of the image, then on the server i am doing the crop with ImageMagick. I know this is bad, but until this bug is fixed, we can follow this scenario.

**Comment by stgunholy** [comment]
Most of cropped images I get have horizontal white line at bottom... My usage is pretty basic:

```
                <img-crop image="ac.photo" result-image="croppedPhotoUrl" result-blob="ac.croppedPhoto" data-flex
                    data-ng-if="ac.photo != null" area-type="rectangle"
                ></img-crop>
```

**Comment by CrackerakiUA** [comment]
I have an project with photographers adding their images, and yes, 80% of the images got that line. I have added cool thing to fix this which i haven't added here yet. Basically i am resizing image before add to the cropper, for example to max + keep scale up to 1920*1080. After that resize no white line exists. I will try to add this soon to the cropper.

**Comment by stgunholy** [comment]
Problem is that I have no idea what size the result image will be :) In my case users can crop image as they want. But I checked demos and on rectangle demo result image turns to be square, if width is bigger then height

**Comment by CrackerakiUA** [comment]
Hmm, i haven't seen that with square. When you allow users crop huge images, like 10mb, cropper will lag even on good computers, so why should you allow that, users wont like it.

**Comment by CrackerakiUA** [comment]
What you could do is resize image before add it to cropper to lower then 1920*1080, take all info from cropper, which area you should crop. Then send to server original image with those information and use imagemagick and do the actual crop there.

**Comment by stgunholy** [comment]
True... But this really destroys 90% of using this component :)

**Comment by CrackerakiUA** [comment]
If you see it like this, i see it as task must be completed )
Besides, i don't know better cropper from this one.
What we need to success is smooth user experience, so i do suggest you to make the way i told you.

**Comment by andrewmadridista** [comment]
I think, problem is in images! Can you look at the original image before cropping? Probably it have transparent line, what later, after cropping, became red, or white, or grey. Am i right?

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
