### ISSUE TITLE
Custom crop border layout

### ISSUE THREAD

**Issue by gr7egor7** [CrackerakiUA/ngImgCropFullExtended#46]
I would be great if we could define different style of  cropping border. For example I wouldn't like to have circle in the square corners or I would like to change border colour.

**Comment by CrackerakiUA** [comment]
Yeah. sounds cool.

**Comment by rickerd** [comment]
I've looked into this feature but all the elements are being drawed on the fly.
All is canvas...

I don't see an option to set this dynamically.
However, there could be multiple styles or definitions of the cropper.

**Comment by rickerd** [comment]
New border in v0.6.0

**Comment by CrackerakiUA** [comment]
Yes, create couple predefined. Still i don't see someone needs it exept @gr7egor7

**Comment by CrackerakiUA** [comment]
Nice @rickerd

**Comment by mitomm** [comment]
I would really like that feature too. 
Personally, I think the style as shown here [https://github.com/alexk111/ngImgCrop] looks really good. Is there any way I could achieve those borders with your module?

**Comment by rickerd** [comment]
I recenty changed the layout of the border.
It now has a look and feel of all major croppers or marquee selection tools.

The border and crop border is made from calculations and rendered as canvas.

Im not seeing it could be custom.
