### ISSUE TITLE
Angular 2.0

### ISSUE THREAD

**Issue by CrackerakiUA** [CrackerakiUA/ngImgCropFullExtended#48]
I believe this plugin must be made in angular 2.0 too. I am planing to recreate it or add code to this project branch, when angular 2 get the release. Is there someone who are interesting in this?

**Comment by oharlem** [comment]
+1

**Comment by camposcristian** [comment]
+1

**Comment by CrackerakiUA** [comment]
I will start this soon, when i do that i will show the link here.

**Comment by Mobius77x** [comment]
+1. Have you started work on this?

**Comment by CrackerakiUA** [comment]
Yes but process it stopped. I will continue with it when angular 2 is released. We have tried to make small app and we saw that ng2 is not ready.

**Comment by cleever** [comment]
Any update on this ?

**Comment by rickerd** [comment]
I think no. @CrackerakiUA did you do any research on Angular 2.0?

**Comment by CrackerakiUA** [comment]
@rickerd same as before, my team tried couple projects on ng2. They are changing things, we didn't like it. We decide to have a look again after 6 months.

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
