### ISSUE TITLE
Could you add this to npm ?

### ISSUE THREAD

**Issue by pgiragossian** [CrackerakiUA/ngImgCropFullExtended#49]

**Comment by CrackerakiUA** [comment]
hmmm, sound cool, yes i will add it as soon as possible.

**Comment by bcb** [comment]
Package needs an `index.js` for webpack or browserify.

node_modules/ng-img-crop-full-extended/index.js

``` javascript
require('./source/js/init.js');
module.exports = 'ngImgCrop';
```

app.js

``` javascript
require('ng-img-crop-full-extended');
angular.module('myApp', ['ngImgCrop', ...
```

**Comment by rdpascua** [comment]
Sadlythis doesn't work in webpack / browserify

**Comment by CrackerakiUA** [comment]
You can create pr with that index.js, i will accept it
