### ISSUE TITLE
Circle bug on resize, going outside canvas.

### ISSUE THREAD

**Issue by peluprvi** [CrackerakiUA/ngImgCropFullExtended#52]
I thought I could use `area-min-size` to limit the selectable area but it is not working as I expected.
I need the circle with a minimum size and it always must be equal or more this size.

``` html
<img-crop image="originalImage" area-type="circle" area-min-size="100" result-image-size="200" chargement="'Loading'" result-image="croppedImage"></img-crop>
```

Edited:
It works without the attribute `area-type`, but the circle is moving while resizing the circle.

And there also an issue on the max size. The circle is going to outside the image.

The behavior that I expect for the selection is:
http://jsfiddle.net/xxo3sk41/1/

**Comment by peluprvi** [comment]
It works without the attribute `area-type`, but the circle is moving while resizing the circle.

**Comment by CrackerakiUA** [comment]
The thing with min max i have in mind to fix those. I believe in 2 weeks i will have a look on this thing. Please work on codepen so it can be relative to others people which work here.

**Comment by rickerd** [comment]
This would be an awesome feature. My skills on JavaScript are not that great but im working on that.
Do you have any idea where it should be altered.

**Comment by CrackerakiUA** [comment]
on crophost

**Comment by amitkumbhar14** [comment]
Hey, Im facing same issue here. and i'd like to know when would you fix this issue? im stuck, cant go further.
Thanx in advance.

**Comment by CrackerakiUA** [comment]
you can go further and fix the issue in the cropper :)

**Comment by amitkumbhar14** [comment]
just solved the issue.... thx nywy

**Comment by CrackerakiUA** [comment]
fixed with latest push

**Comment by amitkumbhar14** [comment]
@CrackerakiUA ... Thx
