### ISSUE TITLE
Crop box shrinks when hitting edge

### ISSUE THREAD

**Issue by francirp** [CrackerakiUA/ngImgCropFullExtended#54]
When moving the box against any of the edges, it shrinks instead of remains the same size. I fixed this for the rectangle area type but am not sure if this works for others. Here are the changes that worked for me: https://github.com/francirp/ngImgCropFullExtended/pull/1

Perhaps there is a better solution that @CrackerakiUA could come up with?

**Comment by peter-tudosa** [comment]
Waiting for this feature also!

**Comment by CrackerakiUA** [comment]
I will checkup in the time i can, at the moment i am full time busy :(
Perhaps in week or two.

**Comment by CrackerakiUA** [comment]
in day or two this will be on.

**Comment by CrackerakiUA** [comment]
try out the new update.
