### ISSUE TITLE
Extending the directive to accept attr as well

### ISSUE THREAD

**Issue by allanesquina** [CrackerakiUA/ngImgCropFullExtended#56]
Hey man, good job, I was searching for this extended features.
How about to allow attribute on the directive?
https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/source/js/ng-img-crop.js#L5

The problem is some older browsers still getting errors with custom elements. I think changing the directive and style to be more generic is a good idea, what do you think?

Regards!

**Comment by CrackerakiUA** [comment]
Hey, thanks.
What do you mean by accept attribute. What if we allow this, how can that help, in which case?

**Comment by allanesquina** [comment]
Hey man, 
allowing attr to be able to avoid custom elements like `<img-crop>` which doesn't work well in older browsers. In this case, I can use `<div img-crop>`

**Comment by CrackerakiUA** [comment]
i got your point

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
