### ISSUE TITLE
Future Plan and Bug List

### ISSUE THREAD

**Issue by CrackerakiUA** [CrackerakiUA/ngImgCropFullExtended#58]
1) Add option to init cropper area to max size as much as possible.

2) Add option to not resize cropper area on siders.

3) Add option to set fixed Height or Width of the crop area.

4) Wrap input(file) within plugin, so it don't have any load problems, like with angular material dialog. Make in it an area with a message inside to click for upload new file. This will be by option enabled. Rebuild all demo with this feature. Add button on work space to add new image if image given, make full options for that.

5) Add filters apply. Make an easy way to create new filters. Add some basic filters like Brightness,Contrast,Blur etc.

6) Add option to export original image resized as dataURL.

7) Add object which will have all values of the crop area

**Comment by rickerd** [comment]
If my code gets merged. 1 is solved partially

**Comment by rickerd** [comment]
7 is done with my PR (if accepted)
