### ISSUE TITLE
Canvas is disappearing

### ISSUE THREAD

**Issue by anitawlosek** [CrackerakiUA/ngImgCropFullExtended#60]
There is problem with this line 
`angular.element(element.children()[element.children().length-1]).remove();`
https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/source/js/ng-img-crop.js#L124

In my code before changing image to another, image is turning to undefined for a moment, so this line is invoking twice and removing canvas too.

**Comment by CrackerakiUA** [comment]
Is this a new bug or old?

**Comment by anitawlosek** [comment]
I just fixed this in my project, but I think it's not save to remove the last element if you are not sure that this element is the one you want to remove.

**Comment by dreamworks** [comment]
same thing here... @anitawlosek did you commit your fix somewhere?

**Comment by dreamworks** [comment]
if (element.children().length > 1) {
    angular.element(element.children()[element.children().length - 1]).remove();
}

worked for me, but definitly more a hack than a fix... (using img-crop within ng-repeat)

**Comment by anitawlosek** [comment]
@dreamworks I changed my code so image isn't turning to undefined, and that solved the problem, but I thing it should be also fixed in this library (maybe get element with some id, instead of any element?)

**Comment by franbueno** [comment]
thanks @dreamworks! It helped me :)

**Comment by CrackerakiUA** [comment]
if you could make a PR, that would be awesome

**Comment by rbrandino1** [comment]
Will be a PR of this problem?

**Comment by rbrandino1** [comment]
There will be a PR of this issue ?

**Comment by rickerd** [comment]
@anitawlosek can you try to test it again?
The code you showed is changed and the `.length - 1]).remove();` is removed.
Maybe it's working now.
I'm closing the issue for now, if the bug is still there you can open it again.
