### ISSUE TITLE
The canvas size is smaller than it supposed to be.

### ISSUE THREAD

**Issue by kawashimaken** [CrackerakiUA/ngImgCropFullExtended#62]
Great project!
I am used to use the old library to create user icon for my old projects.
Now am using this new library and  just try to fill the demo code to my app without modifying it, but I get the smaller cavas area.
Do you have any ideas what I missed?
![pic](https://cloud.githubusercontent.com/assets/12707986/13001201/bff3cee6-d1a6-11e5-98f4-1593a57c955b.png)

Thank you in advance.

**Comment by CrackerakiUA** [comment]
perhaps css issue?

**Comment by kawashimaken** [comment]
All I am using is the copy-n-paste of the demo as the following...(and just changed the width and height to 600x600)

```
.cropArea {
      background: #E4E4E4;
      overflow: hidden;
      width:600px;
      height:600px;
    }
```

I guess that the outer tag in my app might cause the problem, I will dive deeper to investigate later...
EDIT:
I am using ngImgCropFullExtended in my directive, and it will be called into an ui-view, I am guessing it has something to do with some initialization when displayed into an ui-view... 
![pic](https://cloud.githubusercontent.com/assets/12707986/13025346/dfa2277c-d248-11e5-9aa9-324856591afb.png)

**Comment by CrackerakiUA** [comment]
Screenshot is from inspect element or you have added tag canvas?

**Comment by kawashimaken** [comment]
It is from the inspect element, I did't modify anything here.
My guess is that the directive happen to not initialize correctly somehow due to the outside element size.

**Comment by CrackerakiUA** [comment]
image you are testing have big resolution?

**Comment by kawashimaken** [comment]
No, just around 1000x1000 or smaller.
EDIT:
It seems that no matter what I set in cropArea css class, it will looks like the same small size...
![pic](https://cloud.githubusercontent.com/assets/12707986/13034337/d8789304-d375-11e5-8a83-54919b0741cb.png)

**Comment by kawashimaken** [comment]
UPDATE:
Either I set the width to 100% or a certain number, I got the same result as described above.

```
.cropArea {
      background: #E4E4E4;
      overflow: hidden;
      width:600px;  /* or 100%; */
      height:600px;
    }
```

the gray area which is corpArea are correctly shown as configured in cropArea css class,while the canvas is always the same smaller area.  I am wondering if the canvas size setting procedure is working unexpectedly...

@CrackerakiUA Are the code in charge of  canvas size in crop-host.js (https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/source/js/classes/crop-host.js#L81) or anywhere else?

**Comment by CrackerakiUA** [comment]
could be in crop-canvas, i have not touched this part

**Comment by kawashimaken** [comment]
@CrackerakiUA  Thank you for your response.
It turns out that there are some test css code I did not remove containing another canvas css setup which caused this problem.
I happen to have a huge file stack in my current project, it took me long time to find this canvas css.
After removing the suspicious css, all works fine.

Now please close this topic.
Thank you for all your attention and your time!
