### ISSUE TITLE
Get cropbox size

### ISSUE THREAD

**Issue by rickerd** [CrackerakiUA/ngImgCropFullExtended#63]
It would be so nice to do calculations with the height and width of the cropped area.

I know Jcrop has the option to see what the width and height of the crop-area is.

Can i somehow hack into this?

**Comment by CrackerakiUA** [comment]
Perhaps would be great to control that via the controller, have an object for example:
{
windowHeight: xxx,
windowWidth: xxx,
cropHeight: xxx,
cropWidth: xxx,
cropLeft: xxx,
cropTop: xxx,
}
and controller as log as user inside cropper can change those values.
That would solve half of the feature we need.

**Comment by CrackerakiUA** [comment]
I will implement this as soon as possible.

**Comment by rickerd** [comment]
That would be nice. But do you mean that you canset the crop dimensions via the controller and not anymore via the directive html?

**Comment by CrackerakiUA** [comment]
I believe this must be only get for image height width and accessible crop area corners

**Comment by rickerd** [comment]
True. Whats your planning for this feature? If you give me a little directions maybe i can put this one together myself.
I really need the feature haha.

(I need to calculate if the chosen area isn't to small for printing it on a wallpaper-sticker)
That is why i also did some work on the area-init functionality

**Comment by CrackerakiUA** [comment]
well, the plan is:
add option for main directive to accept object.
then if object not given, create object inside that directive.
on crophost use that object to put controllers of crop area in that so it can be modified inside controller which use our plugin.

**Comment by rickerd** [comment]
I will try this one today. Thanks for the information.
One question, why do we need to add the option for the main directive?
Im not clear on that one.

**Comment by CrackerakiUA** [comment]
we need one object, which will be takked from angular controller of the cropper. That object need to be passed into the crophost so that can add all info into it. In that way controller can control the crophost.

**Comment by rickerd** [comment]
Got it working.
http://codepen.io/anon/pen/RrmKwV

**Comment by CrackerakiUA** [comment]
please add more variables like width and height of the cropping image

**Comment by rickerd** [comment]
Why do you want the info about the copping image? This is already givin trough another object.
picFile.$ngfWidth
picFile.$ngfHeight

Also it possible to see the top and left size of the cropper.
http://codepen.io/anon/pen/NxVyjg
This codepen shows how and what.

I don't want to add functionality about the image size since it doesn't add value for the cropject.

**Comment by CrackerakiUA** [comment]
can you show me how $ngfWidth works?
i tried something like this: http://codepen.io/Crackeraki/pen/GoaQdj?editors=1010

**Comment by CrackerakiUA** [comment]
i will tell you one scenario which that will be needed.
for example i need to make half canvas in center, so algorithm will be:
crop width = image width / 2
crop height = image height / 2
crop left = image width / 2 - crop width / 2
crop top = image height / 2 - crop height / 2

**Comment by rickerd** [comment]
Okay, i don't know about the feature. You think it's possible to add to my given feature?
And the height about the image isn't working with block-view what you are using i think..

Maybe there must be done a little more on you block thing, don't really know how it works.

**Comment by CrackerakiUA** [comment]
actually it's not image height and weiget, but crop container height and weight what we need.

**Comment by rickerd** [comment]
Okay. For what i needed the feature its working... I needed to have the cropbox height & width so i can calculate the square meters (m2)
If you want to work together on this thing send me a mssg on Github or e-mail me so we can collab on Skype.

**Comment by CrackerakiUA** [comment]
ok
