### ISSUE TITLE
Selecting image from filesystem cause exception in `setImageSource()`  v0.5.0

### ISSUE THREAD

**Issue by apostnov** [CrackerakiUA/ngImgCropFullExtended#69]
Check this https://github.com/CrackerakiUA/ngImgCropFullExtended/commit/f691c832ccf83d5b994d9d4a920d137b450a2f09#commitcomment-16220664

**Comment by CrackerakiUA** [comment]
i will fix this as soon as i sit on the project. Would be awesome if you make PR, i could accept it right away.
