### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by CrackerakiUA** [CrackerakiUA/ngImgCropFullExtended#72]
Need a help, don't have time to research this.
Which commands make publishing the package correctly?
For example on npm i am doing `npm publish` at the moment.
what should i write for bower to force publish and what on Meteor?

**Comment by rickerd** [comment]
I'll try and find a solution and research it.

**Comment by rickerd** [comment]
Bower is already done and updated automatically due to Github.
Npm is done right by you, i don't have rights to do a npm publish but i would like to... so add me :laughing: 
Meteor is a diffrent framework to build apps with..

I think... we can close the issue

**Comment by CrackerakiUA** [comment]
How can i give you rights to publish in npm?

**Comment by rickerd** [comment]
I don't know? Maybe on the NPM website?
