### ISSUE TITLE
area-min-relative-size and init-max-area not working together

### ISSUE THREAD

**Issue by Talhamansoor** [CrackerakiUA/ngImgCropFullExtended#74]
http://codepen.io/anon/pen/yemZOa

**Comment by Talhamansoor** [comment]
Bug fixed.
https://www.dropbox.com/s/m49xyw0peudlgto/cropextend.rar?dl=0

**Comment by CrackerakiUA** [comment]
If you have modified classes files, please make pr

**Comment by Talhamansoor** [comment]
Blur instead of that greyish image i have modified.
