### ISSUE TITLE
Photos taken with iOS will not load in

### ISSUE THREAD

**Issue by dazulu** [CrackerakiUA/ngImgCropFullExtended#77]
Android tablet, Android phone, Macbook Pro, and Win10 laptop all fine. However, when I select a photo that has been taken with an iPhone (tested 5 and 6s) camera either via file selector or by taking the photo directly, it doesn't load in. It will work with photos transferred to the phone that were not taken via the camera. This is reproduce-able with the standard codepen demos and multiple mobile browsers.

I've had limited success with taking a landscape photo but it really needs to be perfect landscape orientation. Seems to be something to do with how iPhones handle rotation in taken photos? Fix for this would be fantastic. As of right now I just have to disable the ability to use this on iPhones.

**Comment by CrackerakiUA** [comment]
which data cropper accepting? can you put log there?

**Comment by CrackerakiUA** [comment]
when you have an answer, reopen the issue.

**Comment by dazulu** [comment]
Hi. This was actually a duplicate of https://github.com/CrackerakiUA/ngImgCropFullExtended/issues/38. I've added more info there.
