### ISSUE TITLE
Trello

### ISSUE THREAD

**Issue by CrackerakiUA** [CrackerakiUA/ngImgCropFullExtended#78]
If you want to join trello, just reply here with your username in trello and i will add you.

**Comment by rickerd** [comment]
Add me "Rickerd". I don't know what Trello is but i will give it a try.

**Comment by CrackerakiUA** [comment]
It's an really awesome tool, i am using it for many projects. On this cropper i am not active using it right now.

**Comment by angelortiz-dev** [comment]
Hello, please add me aandresortiz, I can add a PR with the fix about this issue https://github.com/CrackerakiUA/ngImgCropFullExtended/issues/129.

**Comment by rickerd** [comment]
Add the PR. Fork this repo and make a PR.
We're not using Trello actively.

We do have chat on Gitter that we actively use.

**Comment by aandresortiz** [comment]
thanks for your reply, the PR is added.

**Comment by rickerd** [comment]
yw, the repo owner is the one to accept or reject PRs.
So far to me it looks okay, as long as the create url still works for all browsers.

**Comment by gercheq** [comment]
@CrackerakiUA can you add me as well? gercek1

**Comment by CrackerakiUA** [comment]
@gercheq we don't use trello anymore.
