### ISSUE TITLE
Update selected image area

### ISSUE THREAD

**Issue by peluprvi** [CrackerakiUA/ngImgCropFullExtended#80]
When select a portrait image and then change it to a landscape image, the cropped image loads wrong.

Code:

``` html
<img-crop
  image="originalImage"
  area-init-size="{w:200, h: 200}"
  init-max-area="true"
  area-min-size="80"
  result-image-size="200"
  chargement="'Loading'"
  result-image-format="'image/jpeg'"
  result-image="croppedImage"
  ng-show="originalImage">
</img-crop>
```

Changing from portrait to landscape:

![image](https://cloud.githubusercontent.com/assets/1561360/13398853/048dc698-dedf-11e5-84f3-a5525b63b97d.png)

After crop:

![image](https://cloud.githubusercontent.com/assets/1561360/13398905/4415957a-dedf-11e5-95ab-767e3827fd6a.png)

This is recalculated after resize the selected area, but not when move the selected area.

**Comment by CrackerakiUA** [comment]
i guess we need cropper restarter

**Comment by CrackerakiUA** [comment]
Can you reproduce this in this codepen? http://codepen.io/Crackeraki/pen/avYNKP
If you do, please give me the images, because i can't with mine.

**Comment by peluprvi** [comment]
The issue occurs when there is no `area-type` setted.

I can reproduce the issue with those options:

``` html
      <img-crop
          image="myImage"
          area-init-size="{w:200, h: 200}"
          init-max-area="true"
          area-min-size="80"
          result-image-size="200"
          chargement="'Loading'"
          result-image-format="'image/jpeg'"
          result-image="myCroppedImage"></img-crop>
```

But there is no issue with those options:

``` html
      <img-crop
          image="myImage"
          area-type="circle"
          area-init-size="{w:200, h: 200}"
          init-max-area="true"
          area-min-size="80"
          result-image-size="200"
          chargement="'Loading'"
          result-image-format="'image/jpeg'"
          result-image="myCroppedImage"></img-crop>
```

The images are:

![456571064_1](https://cloud.githubusercontent.com/assets/1561360/13504817/e50d37c2-e154-11e5-921f-60ae7190bda7.jpg)

![456835260_1](https://cloud.githubusercontent.com/assets/1561360/13504821/e9749b16-e154-11e5-9360-2576bb477f9a.jpg)

**Comment by ohkostya** [comment]
I have a similar issue with these options:

``` html
<img-crop 
    result-image-size="800" 
    area-type="square"
    init-max-area="true"
    area-min-size="80"
    image="myImage" 
    result-image="myCroppedImage"></img-crop>
```

If I upload landscape image the crop area will have a max size. And then if I upload portrait image (without reloading the page) the crop area size will not be in a max size.

**Comment by peluprvi** [comment]
My initial issue was fixed. And I can reproduce the @cuberskulk issue with the same above images.

**Comment by rickerd** [comment]
No need to have a fix since the cropper knows what to load if no area-type is set as user provided as answer.
