### ISSUE TITLE
Which combination of settings to allow the directive to receive values dynamically?

### ISSUE THREAD

**Issue by paulchill** [CrackerakiUA/ngImgCropFullExtended#82]
Great module, i am using this module and love it but i am unsure about one thing.

I wish to be able to allow the directive to receive with and height for the specific images from the aspect ratio. I am using this for various image scenarios, ranging from 1 image to 4 images on one page. 

each image has different height and width, i put in the aspect ratio but it does not seem to give me what i want, when is there a way of working out the relative image height and width based on the aspect ratio, then when an image is loaded in it keeps the ratio?

**Comment by CrackerakiUA** [comment]
Hello
You have confused me a bit :)
Can you please create a code pen with setup which you believe is better in your case and give me scenario with 2-4 images, i would help you.

**Comment by rickerd** [comment]
No response, closing issue
