### ISSUE TITLE
Not working for mobile device or IOS

### ISSUE THREAD

**Issue by midori0507** [CrackerakiUA/ngImgCropFullExtended#87]
I've gone through every ngImgCrop and ios upload via take photo seem doesn't work except in landscape mode.

Digging around and find a gist. It would be nice if this fix was test and applied
https://gist.github.com/hbbh/d5f21c4120665f9429e3
original thread can be found here

https://github.com/alexk111/ngImgCrop/issues/117

**Comment by CrackerakiUA** [comment]
if you are developer, please try to make an pr. If not i will take a look in couple days.

**Comment by midori0507** [comment]
I just create a working pull request, tested on my iphone 5s. As i explained, only make change to crop-host.js file, no idea of change in builded file, i hope i didn't break anything :D
