### ISSUE TITLE
Loading message/popup while render ?

### ISSUE THREAD

**Issue by vinimendes3** [CrackerakiUA/ngImgCropFullExtended#89]
I'm developing an app using Ionic, and I'm using this plugin, and the performance isn't the same as using on web. Seen it, I want to display a message like "Loading..." in a popup turning a circle while it renders the image, and when the render has been complete it finishes.

Is there any way to trigger when does it starts to render and when does it finishes?

Or even better, is there any way to do this render process asynchronously?

Thanks in advance,

**Comment by CrackerakiUA** [comment]
No, and no. :)
there is only a way to trigger process when you want and get response of that call, i believe that will work for you.
http://codepen.io/Crackeraki/pen/XmEdPx

**Comment by rickerd** [comment]
I have a custom include in Angular that adds a loading message.

```
$scope.loader.loading = true;
$scope.loader.message = 'Uw afbeelding word uitgesneden';

<load-indicator data-ng-show="loader.loading"
            message="{% verbatim %}{{loader.message}}{% endverbatim %}"></load-indicator>

.directive('loadIndicator', function () {
    return {
        restrict: "E",
        scope: {
            message: '@'
        },
        template: '<div><div id="overlay"></div>' +
        '<div id="loading">' +
        '<div class="title">{{message || \'Aan het laden\'}}</div></div></div>'
    };
});
```

**Comment by CrackerakiUA** [comment]
@vinimendes3 did that work for you?

**Comment by vinimendes3** [comment]
Sorry @rickerd for the delay. I did not understand very well how you did it. Can you explain better please how did you integrate this code with the ngImgCrop lib? Thanks

**Comment by CrackerakiUA** [comment]
@vinimendes3 basically he create an cover on cropper container. What i could add on cropper is to add variable which would tell outside world that crop is loading.

**Comment by rickerd** [comment]
@CrackerakiUA close this? It's not really an issue
