### ISSUE TITLE
ColorThief Passing Image Twice

### ISSUE THREAD

**Issue by ProdigyView** [CrackerakiUA/ngImgCropFullExtended#93]
I am getting an error that that says:
`ng-img-crop.js:5034 Uncaught TypeError: Cannot read property '0' of null`
Which occurs on this line of code:

```
 ColorThief.prototype.getColor = function(sourceImage, quality) {
        var palette = this.getPalette(sourceImage, 5, quality);
        var dominantColor = palette[0];
        return dominantColor;
    };
```

When I did a console.log(sourceImage) I was getting a weird result. The first result was the image being passed through as correct. But then it passed another image but this string was corrupted. Digging deeper into the code it runs these two functions twice:

```
 scope.$watch(
                function () {
                    return [element[0].clientWidth, element[0].clientHeight];
                },
                function (value) {
                    cropHost.setMaxDimensions(value[0], value[1]);

                    updateResultImage(scope);
                },
                true
            );

 .on('area-move-end area-resize-end image-updated', fnSafeApply(function (scope) {
                    updateResultImage(scope);
                    updateCropject(scope);
                }))

```

Which for some reason the 2nd time its running, passing the bad image through.

**Comment by rickerd** [comment]
Can you make a Codepen? I don't use the Colorthief

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
