### ISSUE TITLE
Gulpfile is creating AMD and CommonJS definitions twice

### ISSUE THREAD

**Issue by tuxtor** [CrackerakiUA/ngImgCropFullExtended#98]
I've been testing ngImgCropFullExtended inside an AngularJS + RequireJS configured project, for instance this library is loaded correctly on development mode (non-optimized nor collapsed libraries), but if you try to optimize the project using r.js (with r.js or grunt-contrib-requirejs), the  application simply does not bootstrap, giving 0 warnings.

As [ng-img-crop.js](https://github.com/CrackerakiUA/ngImgCropFullExtended/blob/master/compile/unminified/ng-img-crop.js) reflects, there are two module definitions involving AMD and CommonJS modules (between lines 3942-3950 and 5661-5669) for ´ColorThief´.

In my tests if I remove the first ColorThief definition I'm able to use ngImgCropFullExtended inside a r.js optimization process.

**Comment by CrackerakiUA** [comment]
I am not familiar with those, if you believe that must be fixed then do PR, i will accept it as long as plugin continue to work.

**Comment by rickerd** [comment]
Since it has been over 2 months and nobody has any knowlegde about the code i'm closing the issue.
